### ISSUE TITLE
Bug with a manualControls and jquery 1.9.1

### ISSUE THREAD

**Issue by yellooo** [woocommerce/FlexSlider#593]
Hi,
i use the the flexslider v2.1 and jquery 1.9.1. And i got this error message:
TypeError: slider.controlNav.live is not a function
jquery.flexslider.js line 203 ( slider.controlNav.live(eventType, function(event) {)

But works on jquery 1.7 and 1.8.

Any idee ?
